/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as CvRouteImport } from './routes/cv'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotographyStoriesRouteImport } from './routes/photography.stories'
import { Route as PhotographySinglesRouteImport } from './routes/photography.singles'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyStoriesRoute = PhotographyStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => PhotographyRoute,
} as any)
const PhotographySinglesRoute = PhotographySinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => PhotographyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/labs': typeof LabsRoute
  '/photography': typeof PhotographyRouteWithChildren
  '/skills': typeof SkillsRoute
  '/photography/singles': typeof PhotographySinglesRoute
  '/photography/stories': typeof PhotographyStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/labs': typeof LabsRoute
  '/photography': typeof PhotographyRouteWithChildren
  '/skills': typeof SkillsRoute
  '/photography/singles': typeof PhotographySinglesRoute
  '/photography/stories': typeof PhotographyStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/labs': typeof LabsRoute
  '/photography': typeof PhotographyRouteWithChildren
  '/skills': typeof SkillsRoute
  '/photography/singles': typeof PhotographySinglesRoute
  '/photography/stories': typeof PhotographyStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cv'
    | '/labs'
    | '/photography'
    | '/skills'
    | '/photography/singles'
    | '/photography/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cv'
    | '/labs'
    | '/photography'
    | '/skills'
    | '/photography/singles'
    | '/photography/stories'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cv'
    | '/labs'
    | '/photography'
    | '/skills'
    | '/photography/singles'
    | '/photography/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CvRoute: typeof CvRoute
  LabsRoute: typeof LabsRoute
  PhotographyRoute: typeof PhotographyRouteWithChildren
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/stories': {
      id: '/photography/stories'
      path: '/stories'
      fullPath: '/photography/stories'
      preLoaderRoute: typeof PhotographyStoriesRouteImport
      parentRoute: typeof PhotographyRoute
    }
    '/photography/singles': {
      id: '/photography/singles'
      path: '/singles'
      fullPath: '/photography/singles'
      preLoaderRoute: typeof PhotographySinglesRouteImport
      parentRoute: typeof PhotographyRoute
    }
  }
}

interface PhotographyRouteChildren {
  PhotographySinglesRoute: typeof PhotographySinglesRoute
  PhotographyStoriesRoute: typeof PhotographyStoriesRoute
}

const PhotographyRouteChildren: PhotographyRouteChildren = {
  PhotographySinglesRoute: PhotographySinglesRoute,
  PhotographyStoriesRoute: PhotographyStoriesRoute,
}

const PhotographyRouteWithChildren = PhotographyRoute._addFileChildren(
  PhotographyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CvRoute: CvRoute,
  LabsRoute: LabsRoute,
  PhotographyRoute: PhotographyRouteWithChildren,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
